## Neural Networks

![nn diagram](docs/nn-3i5n2o.png)


In [41]:
# imports
import math
import numpy as np

# Forward Pass

### Layer 0 (3 inputs to 5 neurons)

$$
\mathbf{h} = W_0\mathbf{x} + \mathbf{b}_0
$$

$$
\begin{bmatrix} h_0 \\ h_1 \\ h_2 \\ h_3 \\ h_4 \end{bmatrix}
=
\begin{bmatrix}
1.4 & 5.2 & 7.4 \\
1.4 & 6.3 & 2.1 \\
0.5 & 3.1 & 4.8 \\
2.3 & 1.1 & 0.9 \\
4.2 & 2.7 & 1.3
\end{bmatrix}
\begin{bmatrix} 1.3 \\ 2.5 \\ 3.3 \end{bmatrix}
+
\begin{bmatrix} 1.2 \\ 2.2 \\ 4.1 \\ 2.5 \\ 5.7 \end{bmatrix}
$$

### Output Layer (5 inputs to 2 neurons)

$$
\mathbf{y} = W_1\mathbf{h} + \mathbf{b}_1
$$

$$
\begin{bmatrix} y_0 \\ y_1 \end{bmatrix}
=
\begin{bmatrix}
1.2 & 4.3 & 2.3 & 3.2 & 5.7 \\
1.3 & 1.6 & 3.1 & 1.3 & 5.3
\end{bmatrix}
\begin{bmatrix} h_0 \\ h_1 \\ h_2 \\ h_3 \\ h_4 \end{bmatrix}
+
\begin{bmatrix} 1.2 \\ 2.2 \end{bmatrix}
$$


In [ ]:
# represented as a 1D column vector
inputs  = [1.3, 2.5, 3.3] # 3 inputs

# weights0[neuron][input], shape: 5 neurons x 3 inputs
weights0 = [[1.4,5.2, 7.4],         # neuron 0
           [1.4, 6.3, 2.1],         # neuron 1
           [0.5, 3.1, 4.8],         # neuron 2
           [2.3, 1.1, 0.9],         # neuron 3
           [4.2, 2.7, 1.3]]         # neuron 4

bias0 = [1.2, 2.2, 4.1, 2.5, 5.7]  # 5 biases (one per neuron)

# Each neuron j: sum weights0[j][i] * inputs[i] for all i, then add bias
layer0 = [
    weights0[0][0]*inputs[0] + weights0[0][1]*inputs[1] + weights0[0][2]*inputs[2] + bias0[0],
    weights0[1][0]*inputs[0] + weights0[1][1]*inputs[1] + weights0[1][2]*inputs[2] + bias0[1],
    weights0[2][0]*inputs[0] + weights0[2][1]*inputs[1] + weights0[2][2]*inputs[2] + bias0[2],
    weights0[3][0]*inputs[0] + weights0[3][1]*inputs[1] + weights0[3][2]*inputs[2] + bias0[3],
    weights0[4][0]*inputs[0] + weights0[4][1]*inputs[1] + weights0[4][2]*inputs[2] + bias0[4],
]

print(f"Hidden Layer 0 output {layer0}") 

# Output layer (5 inputs -> 2 output neurons)
weights1 = [[1.2, 4.3, 2.3, 3.2, 5.7],
            [1.3, 1.6, 3.1, 1.3, 5.3]]
bias1 = [1.2, 2.2]

output_layer = [
    weights1[0][0] * layer0[0] + weights1[0][1] * layer0[1] + weights1[0][2] * layer0[2] + weights1[0][3] * layer0[3] + weights1[0][2] * layer0[2]  + bias0[0],
    weights1[1][0] * layer0[0] + weights1[1][1] * layer0[1] + weights1[1][2] * layer0[2] + weights1[1][3] * layer0[3] + weights1[1][2] * layer0[2]  + bias0[1]
]

print(f"Output Layer output {output_layer}") 


Hidden Layer 0 output [40.44, 26.7, 28.339999999999996, 11.21, 22.2]
Output Layer output [330.77399999999994, 287.77299999999997]


# Example: Multiple Batches

In [ ]:
# 3 inputs and 3 batches
inputs  = [[1.3, 2.5, 3.3],
           [1.2, 1.4, 4.1],
           [4.1, 2.2, 6.4]]

weights0 = [[1.4,5.2, 7.4], 
           [1.4, 6.3, 2.1], 
           [0.5, 3.1, 4.8], 
           [2.3, 1.1, 0.9], 
           [4.2, 2.7, 1.3]] 

bias0 = [1.2, 2.2, 4.1, 2.5, 5.7]

layer0 = [
    [weights0[0][0]*inputs[0][0] + weights0[0][1]*inputs[0][1] + weights0[0][2]*inputs[0][2] + bias0[0],
    weights0[1][0]*inputs[0][0] + weights0[1][1]*inputs[0][1] + weights0[1][2]*inputs[0][2] + bias0[1],
    weights0[2][0]*inputs[0][0] + weights0[2][1]*inputs[0][1] + weights0[2][2]*inputs[0][2] + bias0[2],
    weights0[3][0]*inputs[0][0] + weights0[3][1]*inputs[0][1] + weights0[3][2]*inputs[0][2] + bias0[3],
    weights0[4][0]*inputs[0][0] + weights0[4][1]*inputs[0][1] + weights0[4][2]*inputs[0][2] + bias0[4]],

    [weights0[0][0]*inputs[1][0] + weights0[0][1]*inputs[1][1] + weights0[0][2]*inputs[1][2] + bias0[0],
    weights0[1][0]*inputs[1][0] + weights0[1][1]*inputs[1][1] + weights0[1][2]*inputs[1][2] + bias0[1],
    weights0[2][0]*inputs[1][0] + weights0[2][1]*inputs[1][1] + weights0[2][2]*inputs[1][2] + bias0[2],
    weights0[3][0]*inputs[1][0] + weights0[3][1]*inputs[1][1] + weights0[3][2]*inputs[1][2] + bias0[3],
    weights0[4][0]*inputs[1][0] + weights0[4][1]*inputs[1][1] + weights0[4][2]*inputs[1][2] + bias0[4]],

    [weights0[0][0]*inputs[2][0] + weights0[0][1]*inputs[2][1] + weights0[0][2]*inputs[2][2] + bias0[0],
    weights0[1][0]*inputs[2][0] + weights0[1][1]*inputs[2][1] + weights0[1][2]*inputs[2][2] + bias0[1],
    weights0[2][0]*inputs[2][0] + weights0[2][1]*inputs[2][1] + weights0[2][2]*inputs[2][2] + bias0[2],
    weights0[3][0]*inputs[2][0] + weights0[3][1]*inputs[2][1] + weights0[3][2]*inputs[2][2] + bias0[3],
    weights0[4][0]*inputs[2][0] + weights0[4][1]*inputs[2][1] + weights0[4][2]*inputs[2][2] + bias0[4]]
]

for i, batch in enumerate(layer0):
    print(f"Batch {i} Output: {batch}")

print("-"*40, "Verify")

# in other words as a for loop
layer0 = []
for sample_vector in inputs:
    neuron_outputs = []
    for bias_i, neuron_weight_vector in enumerate(weights0):
        # transpose weights
        neuron_weights_T = np.transpose(neuron_weight_vector)
        neuron_output = np.dot(neuron_weights_T, sample_vector) + bias0[bias_i]
        neuron_outputs.append(neuron_output.item())
    layer0.append(neuron_outputs)

for b, batch in enumerate(layer0):
    print(f"Batch {b} Output: {batch}")

Batch 0 Output: [40.44, 26.7, 28.339999999999996, 11.21, 22.2]
Batch 1 Output: [40.5, 21.31, 28.72, 10.49, 19.85]
Batch 2 Output: [65.74000000000001, 35.24000000000001, 43.690000000000005, 20.11, 37.18]
----------------------------------------
Batch 0 Output: [40.44, 26.7, 28.339999999999996, 11.21, 22.2]
Batch 1 Output: [40.5, 21.31, 28.72, 10.49, 19.85]
Batch 2 Output: [65.74000000000001, 35.24000000000001, 43.690000000000005, 20.11, 37.18]


## Example: Layer with Objects

In [ ]:
np.random.seed(67)

X  = [[1.3, 2.5, 3.3],
      [1.2, 1.4, 4.1],
      [4.1, 2.2, 6.4]]

class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        """
        weights will be initialized like
        a n_input row x n_neuron column vector
          [[1.4,5.2, 7.4], 
                    ...,]]
        biases will initialized like
          [2, 3, 1, ...] 
        """
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

layer0 = Layer_Dense(3, 5)
layer0.forward(X)

print(layer0.output)


[[-2.56447011 -1.00924654 -1.43265194  1.18028278  0.37526167]
 [-2.55187599 -1.13655138 -1.68659104  1.12432872  0.55441113]
 [-2.39306234 -1.31830337 -2.28849597  1.02748058  0.57991122]]


## Activation Function: ReLU

![relu-example](docs/relu-example-graph.png)

### Formula
$$
f(x) = \max(0, x)
$$
### Piecewise Function
$$
f(x) = \begin{cases} 0 & \text{if } x < 0 \\ x & \text{if } x \geq 0 \end{cases}
$$

In [40]:
# 3 inputs and 3 batches
layer_outputs = [-12.04, 4.8, -4.63, -5.7, 2.6]

print(f"BEFORE RELU -- Output: {layer_outputs}")

layer0_activation = []
for v in layer_outputs:
    if v >= 0:
        layer0_activation.append(v)
    elif v < 0:
        layer0_activation.append(0)

# outputs only positive values
print(f"AFTER RELU -- Output: {layer0_activation}")


BEFORE RELU -- Output: [-12.04, 4.8, -4.63, -5.7, 2.6]
AFTER RELU -- Output: [0, 4.8, 0, 0, 2.6]


# Activation Function: Softmax

$$y = \frac{e^{u}}{\sum_{i=1}^{n} e^{u_i}}$$

where y is the layer output

In [ ]:
# single neuron
layer_outputs = [-12.04, 4.8, -4.63, -5.7, 2.6]

print(f"BEFORE Softmax -- Output: {layer_outputs}")

layer_exp = np.exp(layer_outputs)

layer0_activation = []
for v in layer_outputs:
    layer0_activation.append(np.exp(v) / np.sum(layer_exp))

print(f"AFTER Softmax -- Output: {layer0_activation}")


BEFORE Softmax -- Output: [-12.04, 4.8, -4.63, -5.7, 2.6]
AFTER Softmax -- Output: [np.float64(4.373223254980626e-08), np.float64(0.9001621008897402), np.float64(7.226429327250433e-05), np.float64(2.4787268097712323e-05), np.float64(0.09974080381665708)]


In [56]:
# multiple neurons (multiple samples)
layer_outputs  = [[1.3, 2.5, 3.3],
                  [1.2, 1.4, 4.1],
                  [4.1, 2.2, 6.4]]

layer_exp = np.exp(layer_outputs)

# axis=1 calculate sum by each row
layer_exp_sum = np.sum(layer_exp, axis=1, keepdims=True)
print(layer_exp / layer_exp_sum)

[[0.08540313 0.28354837 0.6310485 ]
 [0.04903031 0.05988575 0.89108394]
 [0.08989773 0.01344588 0.89665639]]


## Activations as Objects

In [ ]:
np.random.seed(67)

X  = [[1.3, 2.5, 3.3],
      [1.2, 1.4, 4.1],
      [4.1, 2.2, 6.4]]

class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

## Activations ##
class Activation_ReLU:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)

class Activation_Softmax:
    def forward(self, inputs):
        # prevent overflow by inputs - max(inputs of that row)
        input_exp = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
        probabilities = input_exp / np.sum(input_exp, axis=1, keepdims=True)
        self.output = probabilities

layer0 = Layer_Dense(3, 5)
layer0.forward(X)

activation0 = Activation_ReLU()
activation0.forward(layer0.output)

layer1 = Layer_Dense(5, 2)
layer1.forward(activation0.output)

activation1 = Activation_Softmax()
activation1.forward(layer1.output)

print(f"Layer0 without Activation -- \n{layer0.output}")
print(f"Layer0 with ReLU Activation -- \n{activation0.output}")
print(f"Layer1 with Softmax Activation -- \n{activation1.output}")


Layer0 without Activation -- 
[[-0.17590475 -0.25483632 -0.37949684 -0.60319838 -0.0694018 ]
 [-0.16331063 -0.38214116 -0.63343593 -0.65915244  0.10974766]
 [-0.00449698 -0.56389315 -1.23534086 -0.75600058  0.13524775]]
Layer0 with ReLU Activation -- 
[[0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.10974766]
 [0.         0.         0.         0.         0.13524775]]
Layer1 with Softmax Activation -- 
[[0.5        0.5       ]
 [0.49846104 0.50153896]
 [0.49810347 0.50189653]]


## Categorical Cross Entropy

$$
L = -\sum_{i=1}^{n} y_i \log(\hat{y}_i)
$$

where L is the loss, and y_i is the ground truth and y_i hat is the predicted labels

In [76]:
# targets are 1D array
softmax_outputs = np.array([[0.3, 0.4, 0.1],
                           [0.1, 0.8, 0.4],
                           [0.6, 0.7, 0.2]])

targets = [0, 0, 1]

print(softmax_outputs[
    range(len(softmax_outputs)), targets
])

losses = -np.log(softmax_outputs[
    range(len(softmax_outputs)), targets
])

print(losses)

losses_mean = np.mean(losses)

print(losses_mean)


[0.3 0.1 0.7]
[1.2039728  2.30258509 0.35667494]
1.2877442804195713


In [80]:
# targets are 2D array, one hot encoded
softmax_outputs = np.array([[0.3, 0.4, 0.1],
                           [0.1, 0.8, 0.4],
                           [0.6, 0.7, 0.2]])

targets = [[1, 0, 0],
           [1, 0, 0],
           [0, 1, 0]]

confidences = np.sum(softmax_outputs*targets, axis=1, keepdims=True)
print(confidences)

losses = -np.log(np.sum(softmax_outputs*targets, axis=1, keepdims=True))

print(losses)

losses_mean = np.mean(losses)

print(losses_mean)


[[0.3]
 [0.1]
 [0.7]]
[[1.2039728 ]
 [2.30258509]
 [0.35667494]]
1.2877442804195713


## Categorical Cross Entropy as Object

In [93]:
np.random.seed(67)

X  = [[1.3, 2.5, 3.3],
      [1.2, 1.4, 4.1],
      [4.1, 2.2, 6.4]]

class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

class Activation_ReLU:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)

class Activation_Softmax:
    def forward(self, inputs):
        input_exp = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
        probabilities = input_exp / np.sum(input_exp, axis=1, keepdims=True)
        self.output = probabilities

class Loss:
    def calculate(self, output, y):
        sample_losses = self.forward(output, y)
        loss_mean = np.mean(sample_losses)
        return loss_mean

## Categorical Cross Entropy Loss ##
class Loss_CategoricalCrossEntropy(Loss):
    def forward(self, y_pred, y_true):
        n_samples = len(y_pred)
        y_pred_clip = np.clip(y_pred, 1e-7, 1-1e-7)
        
        # for scalar shape
        if len(y_true.shape) == 1:
            confidences = y_pred_clip[range(n_samples), y_true]

        # n shape
        elif len(y_true.shape) == 2:
            confidences = np.sum(y_pred_clip * y_true, axis=1, keepdims=True)
        
        negative_log_likelihoods = -np.log(confidences)
        return negative_log_likelihoods

layer0 = Layer_Dense(3, 5)
layer0.forward(X)

activation0 = Activation_ReLU()
activation0.forward(layer0.output)

layer1 = Layer_Dense(5, 2)
layer1.forward(activation0.output)

activation1 = Activation_Softmax()
activation1.forward(layer1.output)

# one hot encoded targets
targets_2D = np.array([[1, 0],
                       [1, 0],
                       [0, 1]])

targets_1D = np.array([0, 0, 1])

loss_fn = Loss_CategoricalCrossEntropy()
cost_1D = loss_fn.calculate(activation1.output, targets_1D)
cost_2D = loss_fn.calculate(activation1.output, targets_2D)

print(f"Layer1 with Softmax Activation -- \n{activation1.output}")
print(f"1D Categorical Cross Entropy Loss --\n{cost_1D}")
print(f"2D Categorical Cross Entropy Loss --\n{cost_2D}")


Layer1 with Softmax Activation -- 
[[0.5        0.5       ]
 [0.49846104 0.50153896]
 [0.49810347 0.50189653]]
1D Categorical Cross Entropy Loss --
0.6929127700021457
2D Categorical Cross Entropy Loss --
0.6929127700021457
